# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
#test run :  do docker compose build , then docker compsoe up
services:
  api:
    image: node:22-slim
    port: 3000:3000
    depends_on:
      - db #the api service depends on the db as the api is the bridge
      #the bridge from the database side of things to the clientside
    command: npm run dev

  db:
    image: postgres:17 #postgres version 17
    enviorment: #enviorment varibales in .env
      env_file: .env #sprecifying the name of the env file
      #importing envvairables storing as custom keys
      POSTGRES_USER: {}
      POSTGRES_PASSWORD: {}
      ###########################
      ports: 5432:5432 #(computers port:dockers port one its using)
      volumes: "./src/db/seeder/init.sql/:init.sql" #loads an existing directory u created onto your container
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d ${POSTGRES_DB}"]
        interval: 5s
        timeout: 5s
        retries: 5

# making a framework so other developers can plug into their agents so they can automatically call routes

